### ISSUE TITLE
Question - does it also work for ODM?

### ISSUE THREAD

**Issue by thim81** [4rthem/graphql-mapper#5]
I like the idea of reusing your existing entities/document, but I wonder is it supporting also mongo?

**Comment by 4rthem** [comment]
Yes it should because I used the `ObjectManager` interface in the [`DoctrineResolver`](https://github.com/4rthem/graphql-mapper/blob/master/src/Schema/Resolve/DoctrineResolver.php) class.
So you can inject the `DocumentManager` instead of the `EntityManager`.
