### ISSUE TITLE
Issue Creating Schema

### ISSUE THREAD

**Issue by jralph** [4rthem/graphql-mapper#6]
I'm getting this error when using the schema factory:

```
GraphQL\Schema constructor expects config object now instead of types passed as arguments. See https://github.com/webonyx/graphql-php/issues/36
```

Looking at the referenced link, it appears this has not been updated since this was changed in webonyx/graphql-php.

**Comment by jralph** [comment]
Also, is there any news on this project being maintained, or has it been abandoned. Would be nice to know at the top of the readme if it has.

**Comment by 4rthem** [comment]
Yes this project is abandoned.
I've also updated the README.
